apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j389r5wxl-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/j389r5wxl-java-quarkus-gitops